### ISSUE TITLE
Rename this repo

### ISSUE THREAD

**Issue by davidanthoff** [JuliaEditorSupport/julia-textwrangler-bbedit#4]
If JuliaEditorSupport is the organization that houses support for many different editors, the repos in it should probably have the name of the editor in the repo name.

**Comment by femtotrader** [comment]
This repo should house support for many editors.
A lot of code to automatically generate XML files can probably be shared.
See original discussion https://github.com/JuliaLang/julia/pull/16637
Pinging @tkelman @ViralBShah @IainNZ

**Comment by davidanthoff** [comment]
Ah, sorry, didn't see that!

**Comment by femtotrader** [comment]
My pleasure.
Feel free to help on this project also.

**Comment by femtotrader** [comment]
[JuliaEditorSupport organization](https://github.com/JuliaEditorSupport) seems to take a different approach now.

One repository per editor.

So @davidanthoff , you are right we should rename this repository to `julia-bbedit` for example.

Pinging @tkelman @ViralBShah @IainNZ

**Comment by tkelman** [comment]
If this repo isn't effectively being used for multiple editor modes, then maybe naming more specifically would be preferable

**Comment by davidanthoff** [comment]
We are not using anything here for the VS Code extension. So I agree, renaming this repo seems to make sense to me.

**Comment by oxinabox** [comment]
I came here trying to find the notepad++ language description.
Which used to be in JuliaLang/julia/contrib (or so I thought).

But actually it still is:
https://github.com/JuliaLang/julia/blob/master/contrib/Notepad%2B%2B_2_Julia.ahk
https://github.com/JuliaLang/julia/blob/master/contrib/Julia_Notepad%2B%2B.xml

I still think getting all that out of /contrib is potentially worth doing.
And putting it here.
Though the repo could perhaps still be renamed:
JuliaEditorSupportMisc or Extras or Contrib

**Comment by femtotrader** [comment]
Since there is no script to share code across several editors, I'm ok to rename this repository.

What about `julia-textwrangler-bbedit` or `BBEditTextWrangler-julia`?

An other repository need to be create for Notepad.

What about `julia-notepad-plus-plus`?

**Comment by oxinabox** [comment]
> An other repository need to be create for Notepad.

Thing is, it is not just Notepad++

There are [6 editor supports still there.](https://github.com/JuliaLang/julia/tree/master/contrib#editors---debuggers)

 - ack/ag
 - ctags
 - Colorer
 - GtkSourceView
 - Notepad++ 


And these are all 1 file + readme.
Where as the other repos in the org are bigger, smarted things.

**Comment by femtotrader** [comment]
This repository is renamed julia-textwrangler-bbedit
